package DZ6.db.dao;

import DZ6.db.model.Products;
import DZ6.db.model.ProductsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductsMapper {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.id
     *
     * @mbg.generated Sat Mar 04 20:53:44 VLAT 2023
     */

    long countByExample(ProductsExample example);
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.id
     *
     * @mbg.generated Sat Mar 04 20:53:44 VLAT 2023
     */


    int deleteByExample(ProductsExample example);

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.id
     *
     * @mbg.generated Sat Mar 04 20:53:44 VLAT 2023
     */


    int deleteByPrimaryKey(Long id);

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.id
     *
     * @mbg.generated Sat Mar 04 20:53:44 VLAT 2023
     */


    int insert(Products record);

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.id
     *
     * @mbg.generated Sat Mar 04 20:53:44 VLAT 2023
     */


    int insertSelective(Products record);

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.id
     *
     * @mbg.generated Sat Mar 04 20:53:44 VLAT 2023
     */


    List<Products> selectByExample(ProductsExample example);
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.id
     *
     * @mbg.generated Sat Mar 04 20:53:44 VLAT 2023
     */


    Products selectByPrimaryKey(Long id);

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.id
     *
     * @mbg.generated Sat Mar 04 20:53:44 VLAT 2023
     */


    int updateByExampleSelective(@Param("record") Products record, @Param("example") ProductsExample example);
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.id
     *
     * @mbg.generated Sat Mar 04 20:53:44 VLAT 2023
     */

    int updateByExample(@Param("record") Products record, @Param("example") ProductsExample example);

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.id
     *
     * @mbg.generated Sat Mar 04 20:53:44 VLAT 2023
     */
    int updateByPrimaryKeySelective(Products record);

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.id
     *
     * @mbg.generated Sat Mar 04 20:53:44 VLAT 2023
     */
    int updateByPrimaryKey(Products record);
}